version: '3.5'
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
            - "10380:8080"
    restart: "always"
    volumes:
            - "./jenkins:/var/jenkins_home"

  nexus:
          image: "sonatype/nexus3"
          ports:
                  - "10680:8081"
          volumes:
                  - "./nexus:/nexus-data"
  gitea:
          image: "gitea/gitea:latest"
          ports:
                  - "10122:22"
                  - "10180:3000"
          volumes:
                  - "./gitea:/data"
  sonarqube:
          image: "sonarqube:lts"

          ports:
                  - "10580:9000"

          volumes:
                  - "./sonarqube/conf:/opt/sonarqube/conf"

                  - "./sonarqube/data:/opt/sonarqube/data"

                  - "./sonarqube/logs:/opt/sonarqube/logs"

                  - "./sonarqube/extensions:/opt/sonarqube/extensions"

                  - "./sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins"

  remote_host:
          image: "remote-host"
          build:
                  context: centos7

  postgres:
          image: postgres:12.3
          ports:
                  - "10532:5432"
          environment:
                  - "POSTGRES_USER=postgres"
                  - "POSTGRES_PASSWORD=postgres"
          volumes:
                  - "./postgres/data:/var/lib/postgresql/data"
  neo4j:
          image: neo4j:4.1
          restart: "unless-stopped"
          ports:
                  - "10474:7474"
                  - "10687:7687"
          volumes:
                  - "./neo4j/conf:/conf"
                  - "./neo4j/data:/data"
                  - "./neo4j/import:/import"
                  - "./neo4j/logs:/logs"
                  - "./neo4j/plugins:/plugins"
          environment:
                  - "NEO4J_dbms_memory_pagecache_size=1G"
                  - "NEO4J_dbms.memory.heap.initial_size=1G"
                  - "NEO4J_dbms_memory_heap_max__size=1G"
